# Generated by Django 2.1.5 on 2019-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=models.TextField(max_length=50),
        ),
    ]
