# Generated by Django 2.1.5 on 2019-01-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20190129_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cdate',
        ),
    ]
