# Generated by Django 2.1.7 on 2019-02-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameroomlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipaddress', models.TextField(max_length=50)),
                ('gameaddress', models.TextField(max_length=50)),
                ('wallet_1', models.TextField(max_length=50)),
                ('wallet_2', models.TextField(max_length=50)),
                ('wallet_3', models.TextField(max_length=50)),
            ],
        ),
    ]
